export const ADD_TODO_ATTEMPT = 'ADD_TODO_ATTEMPT';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const GET_TODOS_ATTEMPT = 'GET_TODOS_ATTEMPT';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

export const CHECK_OFF_ATTEMPT = 'CHECK_OFF_ATTEMPT';
export const CHECK_OFF_SUCCESS = 'CHECK_OFF_SUCCESS';
export const CHECK_OFF_FAILURE = 'CHECK_OFF_FAILURE';

export const DELETE_TODO_ATTEMPT = 'DELETE_TODO_ATTEMPT';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';
